disp('Importing data graphical functions');







function polar_Directivity(ant, showIm)
  figure('visible', showIm, 'filename', 'polar directivity');
  hold on;
  
  ant = toVectorShape(ant);
  
  r_grid = 1.3;
  r1 = 1;
  r2 = 1/sqrt(2);
  r3 = 1/sqrt(10);
  grid_handles = [ ...
    polar(linspace(0,2*pi,361), ones(1,361)*r1), ...
    polar(linspace(0,2*pi,361), ones(1,361)*r2), ...
    polar(linspace(0,2*pi,361), ones(1,361)*r3), ...
    polar([0 0], [0 r_grid]), ...
    polar([0 pi/4], [0 r_grid]), ...
    polar([0 pi/2], [0 r_grid]), ...
    polar([0 3*pi/4], [0 r_grid]), ...
    polar([0 pi], [0 r_grid]), ...
    polar([0 5*pi/4], [0 r_grid]), ...
    polar([0 3*pi/2], [0 r_grid]), ...
    polar([0 7*pi/4], [0 r_grid])
  ];
  set(grid_handles, 'color', [.9 .9 .9], 'linewidth', 0.1);
  thick_handles = [
    text(r3*cosd(67.5), r3*sind(67.5), num2str(20*log(r3)), ...
      'horizontalalignment', 'center', ...
      'verticalalignment', 'bottom'), ...
    text(r2*cosd(67.5), r2*sind(67.5), num2str(20*log(r2)), ...
      'horizontalalignment', 'center', ...
      'verticalalignment', 'bottom'), ...
    text(r1*cosd(67.5), r1*sind(67.5), num2str(20*log(r1)), ...
      'horizontalalignment', 'center', ...
      'verticalalignment', 'bottom'), ...
    text(r_grid, 0, "0º"), ...
    text(r_grid*cosd(45), r_grid*sind(45), "45º", ...
      'verticalalignment', 'bottom'), ...
    text(r_grid*cosd(90), r_grid*sind(90), "90º", ...
      'verticalalignment', 'bottom'), ...
    text(r_grid*cosd(135), r_grid*sind(135), "135º", ...
      'horizontalalignment', 'right', ...
      'verticalalignment', 'bottom'), ...
    text(r_grid*cosd(180), r_grid*sind(180), "180º", ...
      'horizontalalignment', 'right'), ...
    text(r_grid*cosd(225), r_grid*sind(225), "225º", ...
      'horizontalalignment', 'right', ...
      'verticalalignment', 'top'), ...
    text(r_grid*cosd(270), r_grid*sind(270), "270º", ...
      'verticalalignment', 'top'), ...
    text(r_grid*cosd(315), r_grid*sind(315), "315º", ...
      'verticalalignment', 'top')
  ];
  
  ids = ant.THETA==90;
  
  THETA = ant.PHI(ids);
  RHO = abs(ant.E(ids));
  h = polar(deg2rad(THETA), RHO);
  set(h, 'color', 'b');
  D = RHO(2:end)-RHO(1:end-1);
  DD = shift(D,-1)-D;
  idsD = find(sign(D) != sign(shift(D,1)));
  if !isempty(idsD)
    idsC = idsD==shift(idsD+1,1);
    idsD(idsC) = [];
    idsDD = idsD(DD(idsD)<0);
    [XDD, YDD] = pol2cart(deg2rad(THETA(idsDD)),RHO(idsDD));
    line(XDD, YDD, 'linestyle', 'none', 'marker', '*', 'color', 'g');
    [XDD, YDD] = pol2cart(deg2rad(THETA(idsDD)),RHO(idsDD)+0.05);
    for i = 1:length(idsDD)
      n = 20*log10(RHO(idsDD(i)));
      n(n*n<1e-2) = 0;
      text(XDD(i), YDD(i), num2str(n,3), ...
        'horizontalalignment', 'center', ...
        'verticalalignment', 'middle');
    end
  end
  
  title('polar directivity');
  axis equal;
  axis off;
  grid on;
  xlabel('x');
  ylabel('y');
end