function trisurf_3Dpolar(PHI, THETA, R, C, name, varargin)
  TRI = delaunay(PHI, THETA);
  
  cp = cosd(PHI);
  sp = sind(PHI);
  ct = cosd(THETA);
  st = sind(THETA);
  
  hfig = figure('visible', 'off');
  set(hfig, 'filename', name);
  colormap('jet');
  hold on;
  trisurf( ...
    TRI, ...
    R.*st.*cp, ...
    R.*st.*sp, ...
    R.*ct, ...
    C, ...
    'linestyle', 'none', ...
    'facecolor', 'interp', ...
    varargin{:});
  colorbar;
  xlabel("x");
  ylabel("y");
  zlabel("z");
end