function electricFields(antenna, showImages)
  
  
##  hfig = figure('visible', showImages);
##  set(hfig, 'filename', 'Electric_Field_sphere');
##  colormap('jet');
##  hold on;
##  trisurf( ...
##    TRI, ...
##    antenna.E.*antenna.samples(1,:), ...
##    antenna.E.*antenna.samples(2,:), ...
##    antenna.E.*antenna.samples(3,:), ...
##    antenna.E_db, ...
##    'linestyle', 'none', ...
##    'facecolor', 'interp');
##  xlabel('x');
##  ylabel('y');
##  zlabel('z');
##  title("Electric field magnitude");
##
##  hfig = figure('visible', showImages);
##  set(hfig, 'filename', 'Electric_Field_Contour');
##  colormap('jet');
##  hold on;
##  trisurf( ...
##    TRI, ...
##    antenna.theta_samples, ...
##    antenna.phi_samples, ...
##    antenna.E_db, ...
##    'linestyle', 'none', ...
##    'facecolor', 'interp');
##  xlabel('theta [degrees]');
##  ylabel('phi [degrees]');
##  title("Electric field magnitude");
end